server:
  port: 8761
  
eureka:
 # instance:
    #hostname: localhost
    #hostname: ${vcap.application.uris[0]:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://ocr-eureka.mybluemix.net/eureka/
#     defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
